### PR TITLE
Feature/517 introduce header component

### PR DESCRIPTION
**Pull request by mingoland**
## Changes in this PR:
- Replicate alpha sprint 7 to beta sprint 1
- Changed organisation name to `HMPPS` according to request from the wider design team

### Before
Screenshot 2020-11-27 at 11 27 03

### After
Screenshot 2020-11-27 at 11 26 49

## Next steps:
We will need to add the `beta` badge after the service name according to the request from the wider team. However technically I found it a bit difficult and I think there will be further discussion on it so I suggest to do it again in another PR. 

Screenshot 2020-11-27 at 12 02 19

### CODE REVIEW

**Comment by Gweaton** [comment]
In the 'after' screenshot, there's no blue label under the page you're on (e.g. my cases, my notifications). I wonder if this is the case on all pages or just one - might need to double check there's not _another_ place we need to update things.

**Comment by mingoland** [comment]
> In the 'after' screenshot, there's no blue label under the page you're on (e.g. my cases, my notifications). I wonder if this is the case on all pages or just one - might need to double check there's not _another_ place we need to update things.

Thanks @Gweaton do you mean the `beta` badge? If so then as I have written in the `Next steps` we will implement it later once we got the code from the wider design team.

**Comment by Gweaton** [comment]
> > In the 'after' screenshot, there's no blue label under the page you're on (e.g. my cases, my notifications). I wonder if this is the case on all pages or just one - might need to double check there's not _another_ place we need to update things.
> 
> Thanks @Gweaton do you mean the `beta` badge? If so then as I have written in the `Next steps` we will implement it later once we got the code from the wider design team.

Sorry, I probably wasn't as clear as I should've been. I meant this blue line here:
image

**Comment by mingoland** [comment]
Ahhhh I see what you meant @Gweaton . Sorry it's misleading only. 

For the root page, we still have the blue line:
Screenshot 2020-11-27 at 14 06 45

The line is missing for inner pages and it's always the case:
Screenshot 2020-11-27 at 14 07 02

So basically this PR won't affect it.

**Review by Gweaton — APPROVED** [review]

**Pull request merged**
