### PR TITLE
Sprint 6 - Monitor: Absence review

### PR DESCRIPTION
**Pull request by Gweaton**
## Changes in this PR

Adds a screen for a probation practitioner to approve/reject a Service user's absence from a scheduled session. Notifications are also updated to allow users to access the "review" page this way.

There isn't currently a design for this, so I've had a go with some prompting from Ming so far.

This currently displays "Missed" for session 2 for all of the "in progress" interventions, so it can be viewed in testing.

### Notification
image

### Review absence page

image

### Intervention progress page with "missed" session

image

## To do:

- Check content makes sense
- Update the intervention session with "acceptable absence" or label to that effect if time/if we think it's important (and designs are available)
- Add a "confirmation" screen once an an absence has been approved/rejected (would be good to get some content for this too).

### CODE REVIEW

**Comment by duffylouise** [comment]
Here's some comments/questions about the review absence page.

The "Session 2: 14/10/20" title is quite hard to read so I thought it might be better to have something like:
Review Macy Flem's absence from session 2
Date: 14/10/20 
Reason for absence: Macy Flem overslept and missed the session

I also wondered if it would be relevant to show attendance for other sessions? 

I think it could be useful to have the free text box for both acceptable and unacceptable absences as users will have to justify their decision either way. So maybe have some text above the box with "Please provide further information"

I think we'll also have to change the text on the CTA button. Once you click the button, does it go to a confirmation page? If so, we could change the button to "save and continue" (or whatever we've used for previous actions where they review the info before confirming).

**Comment by duffylouise** [comment]
For the "missed" label, do we know what happens if an SU misses a session but the intervention can still continue?

**Comment by Gweaton** [comment]
> For the "missed" label, do we know what happens if an SU misses a session but the intervention can still continue?

A good question, will raise this one in Slack I think - might be one to find out from users.

**Review by lawrence-forooghian — APPROVED** [review]
I've addressed the few content tweaks we talked about this morning. Everything else looks good to me, thanks! I'll merge.

**Pull request merged**
